/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {14, 1, 0, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

static const casadi_real casadi_c0[3] = {0., 0., 1.};

/* drone_simple_expl_vde_adj:(i0[10],i1[10],i2[4],i3[])->(o0[14x1,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+10, *w2=w+13, *w3=w+16, *w4=w+20, w5, w6, *w7=w+26, w8, w9, w10, w11, w12, w13, *w14=w+35, *w15=w+38, *w16=w+42, *w17=w+45, *w18=w+48, w19, w20, w21, w22, w23, w24, w25, *w26=w+58, w27, w28, w29, w30, w31, *w32=w+66, w33;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: {@1, @2, @3} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @4 = zeros(4x1) */
  casadi_clear(w4, 4);
  /* #4: @1 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+1 : 0, 3, w1);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @6 = 0.5 */
  w6 = 5.0000000000000000e-01;
  /* #7: @3 = (@6*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #8: {@6, @7} = vertsplit(@3) */
  w6 = w3[0];
  casadi_copy(w3+1, 3, w7);
  /* #9: {@8, @9, @10} = vertsplit(@7) */
  w8 = w7[0];
  w9 = w7[1];
  w10 = w7[2];
  /* #10: @11 = (@5*@10) */
  w11  = (w5*w10);
  /* #11: @12 = @1[2] */
  for (rr=(&w12), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #12: @13 = (@12*@9) */
  w13  = (w12*w9);
  /* #13: @11 = (@11-@13) */
  w11 -= w13;
  /* #14: (@4[1] += @11) */
  for (rr=w4+1, ss=(&w11); rr!=w4+2; rr+=1) *rr += *ss++;
  /* #15: @11 = @1[0] */
  for (rr=(&w11), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @13 = (@11*@9) */
  w13  = (w11*w9);
  /* #17: @5 = (@5*@8) */
  w5 *= w8;
  /* #18: @13 = (@13-@5) */
  w13 -= w5;
  /* #19: (@4[3] += @13) */
  for (rr=w4+3, ss=(&w13); rr!=w4+4; rr+=1) *rr += *ss++;
  /* #20: @12 = (@12*@8) */
  w12 *= w8;
  /* #21: @11 = (@11*@10) */
  w11 *= w10;
  /* #22: @12 = (@12-@11) */
  w12 -= w11;
  /* #23: (@4[2] += @12) */
  for (rr=w4+2, ss=(&w12); rr!=w4+3; rr+=1) *rr += *ss++;
  /* #24: @12 = dot(@1, @7) */
  w12 = casadi_dot(3, w1, w7);
  /* #25: (@4[0] += @12) */
  for (rr=w4+0, ss=(&w12); rr!=w4+1; rr+=1) *rr += *ss++;
  /* #26: @1 = (@6*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #27: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #28: (@4[1:4] += @1) */
  for (rr=w4+1, ss=w1; rr!=w4+4; rr+=1) *rr += *ss++;
  /* #29: @1 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w1);
  /* #30: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #31: @12 = @3[0] */
  for (rr=(&w12), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #32: @14 = @3[1:4] */
  for (rr=w14, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #33: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) *rr++ = (- *cs++ );
  /* #34: @15 = vertcat(@12, @14) */
  rr=w15;
  *rr++ = w12;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #35: @12 = ||@3||_F */
  w12 = sqrt(casadi_dot(4, w3, w3));
  /* #36: @11 = sq(@12) */
  w11 = casadi_sq( w12 );
  /* #37: @15 = (@15/@11) */
  for (i=0, rr=w15; i<4; ++i) (*rr++) /= w11;
  /* #38: @14 = @15[1:4] */
  for (rr=w14, ss=w15+1; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #39: @13 = input[2][0] */
  w13 = arg[2] ? arg[2][0] : 0;
  /* #40: @5 = 14.0056 */
  w5 = 1.4005602240896357e+01;
  /* #41: @2 = (@5*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #42: @16 = (@13*@2) */
  for (i=0, rr=w16, cs=w2; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #43: @17 = (-@16) */
  for (i=0, rr=w17, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #44: @13 = dot(@14, @17) */
  w13 = casadi_dot(3, w14, w17);
  /* #45: @17 = (@1*@13) */
  for (i=0, rr=w17, cr=w1; i<3; ++i) (*rr++)  = ((*cr++)*w13);
  /* #46: (@4[1:4] += @17) */
  for (rr=w4+1, ss=w17; rr!=w4+4; rr+=1) *rr += *ss++;
  /* #47: @17 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w17);
  /* #48: @13 = @17[1] */
  for (rr=(&w13), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #49: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #50: @5 = @15[2] */
  for (rr=(&w5), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #51: {@19, @20, @21} = vertsplit(@16) */
  w19 = w16[0];
  w20 = w16[1];
  w21 = w16[2];
  /* #52: @22 = (@5*@21) */
  w22  = (w5*w21);
  /* #53: @23 = @15[3] */
  for (rr=(&w23), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #54: @24 = (@23*@20) */
  w24  = (w23*w20);
  /* #55: @22 = (@22-@24) */
  w22 -= w24;
  /* #56: (@18[0] += @22) */
  for (rr=w18+0, ss=(&w22); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #57: @22 = @15[1] */
  for (rr=(&w22), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #58: @24 = (@22*@20) */
  w24  = (w22*w20);
  /* #59: @25 = (@5*@19) */
  w25  = (w5*w19);
  /* #60: @24 = (@24-@25) */
  w24 -= w25;
  /* #61: (@18[2] += @24) */
  for (rr=w18+2, ss=(&w24); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #62: @24 = (@23*@19) */
  w24  = (w23*w19);
  /* #63: @25 = (@22*@21) */
  w25  = (w22*w21);
  /* #64: @24 = (@24-@25) */
  w24 -= w25;
  /* #65: (@18[1] += @24) */
  for (rr=w18+1, ss=(&w24); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #66: @24 = @15[0] */
  for (rr=(&w24), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #67: @26 = (@24*@16) */
  for (i=0, rr=w26, cs=w16; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #68: @18 = (@18+@26) */
  for (i=0, rr=w18, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #69: {@25, @27, @28} = vertsplit(@18) */
  w25 = w18[0];
  w27 = w18[1];
  w28 = w18[2];
  /* #70: @29 = (@13*@28) */
  w29  = (w13*w28);
  /* #71: @30 = @17[2] */
  for (rr=(&w30), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #72: @31 = (@30*@27) */
  w31  = (w30*w27);
  /* #73: @29 = (@29-@31) */
  w29 -= w31;
  /* #74: (@4[1] += @29) */
  for (rr=w4+1, ss=(&w29); rr!=w4+2; rr+=1) *rr += *ss++;
  /* #75: @29 = @17[0] */
  for (rr=(&w29), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #76: @27 = (@29*@27) */
  w27  = (w29*w27);
  /* #77: @31 = (@13*@25) */
  w31  = (w13*w25);
  /* #78: @27 = (@27-@31) */
  w27 -= w31;
  /* #79: (@4[3] += @27) */
  for (rr=w4+3, ss=(&w27); rr!=w4+4; rr+=1) *rr += *ss++;
  /* #80: @25 = (@30*@25) */
  w25  = (w30*w25);
  /* #81: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #82: @25 = (@25-@28) */
  w25 -= w28;
  /* #83: (@4[2] += @25) */
  for (rr=w4+2, ss=(&w25); rr!=w4+3; rr+=1) *rr += *ss++;
  /* #84: @17 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w17);
  /* #85: @25 = dot(@17, @18) */
  w25 = casadi_dot(3, w17, w18);
  /* #86: (@4[0] += @25) */
  for (rr=w4+0, ss=(&w25); rr!=w4+1; rr+=1) *rr += *ss++;
  /* #87: @25 = (2.*@12) */
  w25 = (2.* w12 );
  /* #88: @15 = (@15/@11) */
  for (i=0, rr=w15; i<4; ++i) (*rr++) /= w11;
  /* #89: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<4; ++i) *rr++ = (- *cs++ );
  /* #90: @32 = zeros(4x1) */
  casadi_clear(w32, 4);
  /* #91: @28 = @3[0] */
  for (rr=(&w28), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #92: @17 = (@17*@28) */
  for (i=0, rr=w17; i<3; ++i) (*rr++) *= w28;
  /* #93: @28 = @3[2] */
  for (rr=(&w28), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #94: @27 = (@28*@30) */
  w27  = (w28*w30);
  /* #95: @31 = @3[3] */
  for (rr=(&w31), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #96: @33 = (@31*@13) */
  w33  = (w31*w13);
  /* #97: @27 = (@27-@33) */
  w27 -= w33;
  /* #98: @31 = (@31*@29) */
  w31 *= w29;
  /* #99: @33 = @3[1] */
  for (rr=(&w33), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #100: @30 = (@33*@30) */
  w30  = (w33*w30);
  /* #101: @31 = (@31-@30) */
  w31 -= w30;
  /* #102: @33 = (@33*@13) */
  w33 *= w13;
  /* #103: @28 = (@28*@29) */
  w28 *= w29;
  /* #104: @33 = (@33-@28) */
  w33 -= w28;
  /* #105: @18 = vertcat(@27, @31, @33) */
  rr=w18;
  *rr++ = w27;
  *rr++ = w31;
  *rr++ = w33;
  /* #106: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #107: @27 = @17[2] */
  for (rr=(&w27), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #108: @31 = (@27*@20) */
  w31  = (w27*w20);
  /* #109: @33 = @17[1] */
  for (rr=(&w33), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #110: @28 = (@33*@21) */
  w28  = (w33*w21);
  /* #111: @31 = (@31-@28) */
  w31 -= w28;
  /* #112: (@32[1] += @31) */
  for (rr=w32+1, ss=(&w31); rr!=w32+2; rr+=1) *rr += *ss++;
  /* #113: @31 = @17[0] */
  for (rr=(&w31), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #114: @21 = (@31*@21) */
  w21  = (w31*w21);
  /* #115: @28 = (@27*@19) */
  w28  = (w27*w19);
  /* #116: @21 = (@21-@28) */
  w21 -= w28;
  /* #117: (@32[2] += @21) */
  for (rr=w32+2, ss=(&w21); rr!=w32+3; rr+=1) *rr += *ss++;
  /* #118: @19 = (@33*@19) */
  w19  = (w33*w19);
  /* #119: @20 = (@31*@20) */
  w20  = (w31*w20);
  /* #120: @19 = (@19-@20) */
  w19 -= w20;
  /* #121: (@32[3] += @19) */
  for (rr=w32+3, ss=(&w19); rr!=w32+4; rr+=1) *rr += *ss++;
  /* #122: @18 = @3[1:4] */
  for (rr=w18, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #123: @19 = dot(@18, @1) */
  w19 = casadi_dot(3, w18, w1);
  /* #124: @18 = (@19*@16) */
  for (i=0, rr=w18, cs=w16; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #125: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #126: (@32[1:4] += @18) */
  for (rr=w32+1, ss=w18; rr!=w32+4; rr+=1) *rr += *ss++;
  /* #127: @20 = dot(@17, @16) */
  w20 = casadi_dot(3, w17, w16);
  /* #128: (@32[0] += @20) */
  for (rr=w32+0, ss=(&w20); rr!=w32+1; rr+=1) *rr += *ss++;
  /* #129: @20 = dot(@15, @32) */
  w20 = casadi_dot(4, w15, w32);
  /* #130: @25 = (@25*@20) */
  w25 *= w20;
  /* #131: @25 = (@25/@12) */
  w25 /= w12;
  /* #132: @15 = (@25*@3) */
  for (i=0, rr=w15, cs=w3; i<4; ++i) (*rr++)  = (w25*(*cs++));
  /* #133: @4 = (@4+@15) */
  for (i=0, rr=w4, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #134: @32 = (@32/@11) */
  for (i=0, rr=w32; i<4; ++i) (*rr++) /= w11;
  /* #135: {@11, @16} = vertsplit(@32) */
  w11 = w32[0];
  casadi_copy(w32+1, 3, w16);
  /* #136: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #137: (@4[1:4] += @16) */
  for (rr=w4+1, ss=w16; rr!=w4+4; rr+=1) *rr += *ss++;
  /* #138: (@4[0] += @11) */
  for (rr=w4+0, ss=(&w11); rr!=w4+1; rr+=1) *rr += *ss++;
  /* #139: output[0][1] = @4 */
  if (res[0]) casadi_copy(w4, 4, res[0]+3);
  /* #140: @17 = (@24*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #141: @14 = (@19*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #142: @17 = (@17-@14) */
  for (i=0, rr=w17, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #143: @19 = (@33*@23) */
  w19  = (w33*w23);
  /* #144: @24 = (@27*@5) */
  w24  = (w27*w5);
  /* #145: @19 = (@19-@24) */
  w19 -= w24;
  /* #146: @27 = (@27*@22) */
  w27 *= w22;
  /* #147: @23 = (@31*@23) */
  w23  = (w31*w23);
  /* #148: @27 = (@27-@23) */
  w27 -= w23;
  /* #149: @31 = (@31*@5) */
  w31 *= w5;
  /* #150: @33 = (@33*@22) */
  w33 *= w22;
  /* #151: @31 = (@31-@33) */
  w31 -= w33;
  /* #152: @14 = vertcat(@19, @27, @31) */
  rr=w14;
  *rr++ = w19;
  *rr++ = w27;
  *rr++ = w31;
  /* #153: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #154: @19 = dot(@17, @2) */
  w19 = casadi_dot(3, w17, w2);
  /* #155: output[0][2] = @19 */
  if (res[0]) res[0][7] = w19;
  /* #156: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #157: @19 = @3[3] */
  for (rr=(&w19), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #158: @27 = (@19*@9) */
  w27  = (w19*w9);
  /* #159: @31 = @3[2] */
  for (rr=(&w31), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #160: @33 = (@31*@10) */
  w33  = (w31*w10);
  /* #161: @27 = (@27-@33) */
  w27 -= w33;
  /* #162: (@17[0] += @27) */
  for (rr=w17+0, ss=(&w27); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #163: @27 = @3[1] */
  for (rr=(&w27), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #164: @10 = (@27*@10) */
  w10  = (w27*w10);
  /* #165: @19 = (@19*@8) */
  w19 *= w8;
  /* #166: @10 = (@10-@19) */
  w10 -= w19;
  /* #167: (@17[1] += @10) */
  for (rr=w17+1, ss=(&w10); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #168: @31 = (@31*@8) */
  w31 *= w8;
  /* #169: @27 = (@27*@9) */
  w27 *= w9;
  /* #170: @31 = (@31-@27) */
  w31 -= w27;
  /* #171: (@17[2] += @31) */
  for (rr=w17+2, ss=(&w31); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #172: @31 = @3[0] */
  for (rr=(&w31), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #173: @7 = (@31*@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #174: @17 = (@17+@7) */
  for (i=0, rr=w17, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #175: @7 = @3[1:4] */
  for (rr=w7, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #176: @7 = (@6*@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #177: @17 = (@17-@7) */
  for (i=0, rr=w17, cs=w7; i<3; ++i) (*rr++) -= (*cs++);
  /* #178: output[0][3] = @17 */
  if (res[0]) casadi_copy(w17, 3, res[0]+8);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 71;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
